---
Description: This template contains the security groups required by our ECS Cluster
              for the DI reference architecture.
# OPTIONAL Parameters section to customize your templates. 
# Parameters enable you to input custom values to your template each 
# time you create or update a stack.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the security groups should be deployed to
# REQUIRED Resources section declares the AWS resources that you want to 
# include in the stack, such as an Amazon EC2 instance or an Amazon S3 bucket.
Resources:
  ECSHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the ECS hosts and the tasks/containers that run
        on them
      SecurityGroupIngress:
      - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
        # For allowed numbers see: http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
        # If you specify -1, or a protocol number other than tcp, udp, icmp, or 58 (ICMPv6), 
        # traffic on all ports is allowed, regardless of any ports you specify. 
        #For tcp, udp, and icmp, you must specify a port range. For protocol 58 (ICMPv6), 
        # you can optionally specify a port range; if you don't, traffic for all types and 
        # codes is allowed
        IpProtocol: -1
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-ECS-Hosts
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the load balancer that sits in front of ECS
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: -1
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-LoadBalancers
Outputs:
  ECSHostSecurityGroup:
    Description: A reference to the security group for ECS hosts
    Value: !Ref ECSHostSecurityGroup
  LoadBalancerSecurityGroup:
    Description: A reference to the security group for load balancers
    Value: !Ref LoadBalancerSecurityGroup
...
