---
AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation Template provisions an initial sys-admin for the
  multi-tenant identity platform
Parameters:
  Domain:
    Description: The Service Domain Obtained from API Gateway
    Type: String
  Protocol:
    Description: The Protocol for the Request
    Type: String
    Default: https://
  Path:
    Description: The Path for the request.
    Type: String
    Default: /sys/admin
  Body:
    Description: The Content for POST Request in JSON Format
    Type: String
  Method:
    Description: The Type of Method. (Only "POST", "GET", or "DELETE")
    Type: String
    Default: POST
  S3Bucket:
    Description: The S3 Bucket Name
    Type: String
  S3BucketPrefix:
    Description: The S3 Bucket Prefix
    Type: String
Resources:
  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: ConfigPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: Logging
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
  CreateSysAdmin:
    Type: Custom::ConfigFile
    Properties:
      ServiceToken: !GetAtt UpdateConfigFunction.Arn
      Domain: !Ref Domain
      Protocol: !Ref Protocol
      Path: !Ref Path
      Body: !Ref Body
      Method: !Ref Method
  UpdateConfigFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Creates the System Admin for the Multi-Tenant Identity Platform
      Handler: index.handler
      Runtime: python2.7
      Role: !GetAtt ConfigRole.Arn
      Timeout: 300
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub ${S3BucketPrefix}/functions/packages/rest-request-create/rest-request-create.zip
...
