---
AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation Template invokes other templates responsible for
  cleaning up AWS Resources
Parameters:
  QSS3BucketName:
    Description: The Template Bucket Name.
    Type: String
  QSS3KeyPrefix:
    Description: The Template Bucket Prefix.
    Type: String
  Bucket:
    Description: The Bucket which should be emptied.
    Type: String
  Repository:
    Description: The ECR Repository to remove.
    Type: String
  RoleArn:
    Description: The ARN of the Cleanup Role.
    Type: String
Resources:
  BucketCleanup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}/templates/ref-arch-clean-bucket.yml
      Parameters:
        Bucket: !Ref Bucket
        ServiceToken: !Ref RoleArn
  RepositoryCleanup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}/templates/ref-arch-clean-repository.yml
      Parameters:
        Repository: !Ref Repository
        ServiceToken: !Ref RoleArn
...
